# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
# BLOAT OS Bootloader configuration
---
# Bootloader to install
bootLoader: grub

# Install GRUB to MBR
gubInstall:
    target: /boot/grub
    installEFIFallback: true

# EFI directory
efi:
    directory: /boot/efi

# Kernel parameters
kernelParams: []

# Keep bootloader config
keepBootLoader: false
