# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# BLOAT OS Display Manager Configuration
# Enable SDDM.
---
displaymanagers:
  - sddm

defaultDesktopEnvironment:
    executable: startplasma-x11
    desktopFile: plasma

# Basic SDDM configuration
basicSetup: false
