# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# BLOAT OS Finished Module
# Just says "done".
---
restartNowEnabled: true
restartNowCommand: "systemctl -i reboot"

# No install log
installLogFile: "/var/log/calamares.log"

# No redirect
redirectToUrl: false
