# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
# BLOAT OS GRUB configuration
---
# Keep existing GRUB config
keepDistributor: false

# Distributor name
distributor: BLOAT OS

# GRUB configuration file
grubCfg: /boot/grub/grub.cfg

# EFI boot directory
efiBootloaderId: bloatos
