# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
# BLOAT OS initcpio configuration
---
# Update initramfs after installation
update: true

# Modules to add
modules: []

# Binaries to add
binaries: []

# Files to add
files: []

# Hooks
hooks: []
