# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# BLOAT OS Mount Configuration
---
# Mount options
mountOptions:
    default: defaults,noatime

# Crypttab
crypttab:
    entry: 

# Extra mounts (for btrfs subvolumes or similar)
extraMounts:
    - device: proc
      fs: proc
      mountPoint: /proc
    - device: sys
      fs: sysfs
      mountPoint: /sys
    - device: /dev
      fs: bind
      mountPoint: /dev
    - device: /run
      fs: bind
      mountPoint: /run

# LUKS settings
luksGeneration: luks2
luksName: luks
luksEncryptAll: true

# Swap file
swapFile:
    reuse: true
    filename: swapfile
