# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
# BLOAT OS Network Configuration
# Enable NetworkManager.
---
# Enable systemd-networkd or NetworkManager
systemd: true

# NetworkManager
networkmanager: true

# Wicked
wicked: false
