# BLOAT OS Calamares Package Operations
---
backend: pacman
skip_if_no_internet: false
update_db: false
update_system: false
pacman:
    num_retries: 3
    disable_download_timeout: false
    needed_only: false
operations:
  - try_remove:
    - mkinitcpio-archiso
    - alci-calamares
    - alci-calamares-config
    - alci-dwm
    - hwinfo
    - squashfs-tools
    - xorg-xinit
    - xorg-apps
    - xterm
    - xdg-utils
    - xclip
