# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# BLOAT OS Partition Configuration
---
partition:
    backend: kpmcore

# Allow manual partitioning
allowManualPartitioning:    true

# EFI settings
efi:
    systemPartitionSize:        300M
    mountPoint:                 /boot/efi
    label:                      EFI
    shouldBeEncrypted:          false

# Initial partitioning choices
initialPartitioningChoice:    none
initialSwapChoice:          none

# Partition layout options
availablePartitionLayout:
    - name:      "BLOAT OS Default"
      description: "Root partition with everything (MAXIMUM BLOAT)"
      partitions:
        - mountPoint: /
          size: 100%
          fs: ext4

# Show advanced features
showAllocateSpace:          true
