# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
# BLOAT OS Preserve Files
# Files to keep on the installed system.
---
preserve:
    - /etc/xdg/plasmasetuprc
    - /etc/bloatos
    - /etc/systemd/system/plasma-setup.service
    - /etc/systemd/system/bloat-install.service
    - /usr/share/plasma/packages/org.kde.plasmasetup.bloatinstall
