# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
# BLOAT OS Remove User
# Remove the live ISO user (root autologin) from target system.
---
# User to remove
user: root

# Remove autologin
removeAutologin: true
