# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
# BLOAT OS Services Configuration
# Enable services on installed system.
---
# Services to enable
services:
    - name: NetworkManager
      enabled: true
    - name: sddm
      enabled: true
    - name: plasma-setup
      enabled: true
    - name: bloat-install
      enabled: true

# Services to disable
services-disabled: []
