# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# BLOAT OS Pre-Install Script
# Runs before package installation.
---
script:
    - echo "BLOAT OS: Pre-installation setup..."
    - ""
