# BLOAT OS shellprocess-final
---
dontChroot: false
timeout: 999
script:
    - "-rm ${ROOT}/etc/sudoers.d/g_wheel"
    - "-rm ${ROOT}/etc/systemd/system/getty@tty1.service.d"
    - "-rm -r ${ROOT}/etc/systemd/system/multi-user.target.wants/pacman-init.service"
    - "-rm ${ROOT}/etc/systemd/system/pacman-init.service"
    - "-rm ${ROOT}/etc/systemd/system/etc-pacman.d-gnupg.mount"
    - "-rm ${ROOT}/root/.automated_script.sh"
    - "-rm ${ROOT}/root/.zlogin"
    - "-rm ${ROOT}/etc/polkit-1/rules.d/49-nopasswd_global.rules"
    - "-rm ${ROOT}/usr/local/bin/alci-make-a-pure-arch"
    - "-rm ${ROOT}/usr/local/bin/alci-displaymanager-check"
    - "-rm ${ROOT}/usr/local/bin/alci-virtual-machine-check"
    - "-rm ${ROOT}/usr/local/bin/get-nemesis-on-alci"
    - "-rm ${ROOT}/usr/local/bin/get-chadwm"
    - "-rm ${ROOT}/usr/local/bin/alci-*"
    - "-rm ${ROOT}/usr/local/bin/bloatos-live-start"
