# BLOAT OS Welcome Module
---
showSupportUrl:         false
showKnownIssuesUrl:     false
showReleaseNotesUrl:    false
showDonateUrl:          false
requirements:
    requiredStorage:    50
    requiredRam:        2.0
    internetCheckUrl:   http://example.com
    check:
        - storage
        - ram
        - power
        - screen
    required:
        - storage
        - ram
geoip:
    style:    "json"
    url:      "https://geoip.kde.org/v1/calamares"
    selector: ""
